# Generated by Django 4.2.4 on 2023-08-22 22:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 39, 55, 390680, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('dimension', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 39, 55, 390680, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('episode', models.CharField(max_length=150)),
                ('air_date', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 39, 55, 390680, tzinfo=datetime.timezone.utc))),
                ('mainCharacter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='app_rick.characters')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='species',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='app_rick.species'),
        ),
    ]
