# Generated by Django 4.2.4 on 2023-08-22 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_rick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 44, 18, 807950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 44, 18, 807950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 44, 18, 807950, tzinfo=datetime.timezone.utc))),
                ('species', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='app_rick.species')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='mainCharacter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='app_rick.character'),
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
    ]
