# Generated by Django 4.2.4 on 2023-08-22 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rick', '0002_alter_episode_air_date_alter_locations_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('dimension', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 48, 47, 113996, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.RenameModel(
            old_name='Species',
            new_name='Specie',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AlterField(
            model_name='character',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 48, 47, 113996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 22, 48, 47, 113996, tzinfo=datetime.timezone.utc)),
        ),
    ]
